// To parse this JSON data, do
//
//     final attendanceModel = attendanceModelFromJson(jsonString);

import 'dart:convert';

AttendanceModel attendanceModelFromJson(String str) => AttendanceModel.fromJson(json.decode(str));

String attendanceModelToJson(AttendanceModel data) => json.encode(data.toJson());

class AttendanceModel {
  String? id;
  DateTime? date;
  DateTime? checkInTime;
  double? checkInLat;
  double? checkInLng;
  String? checkInPhoto;
  bool? checkInInsideRadius;
  DateTime? checkOutTime;
  double? checkOutLat;
  double? checkOutLng;
  String? status;
  int? durationMinutes;
  int? points;
  bool? isAutoGenerated;
  String? employeeId;
  String? branchId;
  DateTime? createdAt;
  DateTime? updatedAt;

  AttendanceModel({
    this.id,
    this.date,
    this.checkInTime,
    this.checkInLat,
    this.checkInLng,
    this.checkInPhoto,
    this.checkInInsideRadius,
    this.checkOutTime,
    this.checkOutLat,
    this.checkOutLng,
    this.status,
    this.durationMinutes,
    this.points,
    this.isAutoGenerated,
    this.employeeId,
    this.branchId,
    this.createdAt,
    this.updatedAt,
  });

  factory AttendanceModel.fromJson(Map<String, dynamic> json) => AttendanceModel(
    id: json["id"],
    date: json["date"] == null ? null : DateTime.parse(json["date"]).toLocal(),
    checkInTime: json["checkInTime"] == null ? null : DateTime.parse(json["checkInTime"]).toLocal(),
    checkInLat: json["checkInLat"]?.toDouble(),
    checkInLng: json["checkInLng"]?.toDouble(),
    checkInPhoto: json["checkInPhoto"],
    checkInInsideRadius: json["checkInInsideRadius"],
    checkOutTime: json["checkOutTime"] == null ? null : DateTime.parse(json["checkOutTime"]).toLocal(),
    checkOutLat: json["checkOutLat"]?.toDouble(),
    checkOutLng: json["checkOutLng"]?.toDouble(),
    status: json["status"],
    durationMinutes: json["durationMinutes"],
    points: json["points"],
    isAutoGenerated: json["isAutoGenerated"],
    employeeId: json["employeeId"],
    branchId: json["branchId"],
    createdAt: json["createdAt"] == null ? null : DateTime.parse(json["createdAt"]).toLocal(),
    updatedAt: json["updatedAt"] == null ? null : DateTime.parse(json["updatedAt"]).toLocal(),
  );

  Map<String, dynamic> toJson() => {
    "id": id,
    "date": date?.toIso8601String(),
    "checkInTime": checkInTime?.toIso8601String(),
    "checkInLat": checkInLat,
    "checkInLng": checkInLng,
    "checkInPhoto": checkInPhoto,
    "checkInInsideRadius": checkInInsideRadius,
    "checkOutTime": checkOutTime?.toIso8601String(),
    "checkOutLat": checkOutLat,
    "checkOutLng": checkOutLng,
    "status": status,
    "durationMinutes": durationMinutes,
    "points": points,
    "isAutoGenerated": isAutoGenerated,
    "employeeId": employeeId,
    "branchId": branchId,
    "createdAt": createdAt?.toIso8601String(),
    "updatedAt": updatedAt?.toIso8601String(),
  };
}
